### ISSUE TITLE
Issue with non-root user?

### ISSUE THREAD

**Issue by ZenJakey** [Didstopia/7dtd-server#28]
When I try running the docker image, I get that the chown operation is not permitted before installing/updating steamcmd here:
```
server_1  | ╔═════════════════════════════════════════════════╗
server_1  | ║    _____  _     _     _              _          ║
server_1  | ║   |  __ \(_)   | |   | |            (_)         ║
server_1  | ║   | |  | |_  __| |___| |_ ___  _ __  _  __ _    ║
server_1  | ║   | |  | | |/ _| / __| __/ _ \| |_ \| |/ _| |   ║
server_1  | ║   | |__| | | (_| \__ \ || (_) | |_) | | (_| |   ║
server_1  | ║   |_____/|_|\__|_|___/\__\___/| |__/|_|\__|_|   ║
server_1  | ║                               | |               ║
server_1  | ║                               |_|               ║
server_1  | ╠═════════════════════════════════════════════════╣
server_1  | ║ You are using an image that is based on         ║
server_1  | ║ a base image maintained by Didstopia.           ║
server_1  | ║                                                 ║
server_1  | ║ For more information:                           ║
server_1  | ║ https://github.com/Didstopia/docker-base-images ║
server_1  | ╚═════════════════════════════════════════════════╝
server_1  |
server_1  |
server_1  | Running as user: docker
server_1  | Using branch arguments: public
server_1  | chown: changing ownership of '/steamcmd/7dtd': Operation not permitted
server_1  | Installing/updating steamcmd..
server_1  | x linux32/
server_1  | x linux32/libstdc++.so.6
server_1  | x linux32/steamcmd
server_1  | x steamcmd.sh
server_1  | x steam.sh
```
And that seems to cause an issue with installing the game files here:
```
server_1  | Connecting anonymously to Steam Public...Logged in OK
server_1  | Waiting for user info...OK
server_1  | force_install_dir /steamcmd/7dtd
server_1  | app_update 294420 public validate
server_1  | ERROR! Failed to install app '294420' (Disk write failure)
server_1  | quit
```

Following is my docker-compose file I'm using to set up the ports and volumes. (I removed IPs from the ports section of the yml)
```
version: "3.3"
services:
  server:
    image: didstopia/7dtd-server
    env_file:
      - ./rust.env
    ports:
      - "26900:26900/tcp"
      - "26900:26900/udp"
      - "26901:26901/udp"
      - "26902:26902/udp"
      - "8080:8080/tcp"
      - "8081:8081/tcp"
    volumes:
      - type: volume
        source: ./serverFiles
        target: /steamcmd/7dtd
      - type: volume
        source: ./serverConfig
        target: /app/.local/share/7DaysToDie
```
Any help would be much appreciated.
