### ISSUE TITLE
UnauthorizedAccessException: Access to the path "/home/sdtd" is denied

### ISSUE THREAD

**Issue by tonymmm1** [Didstopia/7dtd-server#34]
Running container with bind-mount and with volume fails. Seems to be either issue with binary or file permissions running as user?

docker-compose.yml
```
version: "3.7"
services:
  7dtd:
    image: didstopia/7dtd-server
    container_name: 7dtd
#    user: 1000:1000
    ports:
      - 2100:26900
#    environment:
#      - SEVEN_DAYS_TO_DIE_START_MODE="0"
#      - SEVEN_DAYS_TO_DIE_UPDATE_CHECKING="0"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - 7dtd_data:/steamcmd/7dtd
      - 7dtd_game:/app/.local/share/7DaysToDie
      - ./serverconfig.xml:/app/.local/share/7DaysToDie/serverconfig.xml
    restart: always

volumes:
  7dtd_data:
  7dtd_game:
```
docker-compose logs
```
7dtd    | UnauthorizedAccessException: Access to the path "/home/sdtd" is denied.
7dtd    |   at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x0005e] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 
7dtd    |   at System.IO.Directory.CreateDirectory (System.String path) [0x0008f] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 
7dtd    |   at System.IO.DirectoryInfo.Create () [0x00000] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 
7dtd    |   at (wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.Create()
7dtd    |   at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x00036] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 
7dtd    |   at System.IO.Directory.CreateDirectory (System.String path) [0x0008f] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 
7dtd    |   at System.IO.DirectoryInfo.Create () [0x00000] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 
7dtd    |   at (wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.Create()
7dtd    |   at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x00036] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 
7dtd    |   at System.IO.Directory.CreateDirectory (System.String path) [0x0008f] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 
7dtd    |   at System.IO.DirectoryInfo.Create () [0x00000] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 
7dtd    |   at (wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.Create()
7dtd    |   at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x00036] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 
7dtd    |   at System.IO.Directory.CreateDirectory (System.String path) [0x0008f] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 
7dtd    |   at System.IO.DirectoryInfo.Create () [0x00000] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 
7dtd    |   at (wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.Create()
7dtd    |   at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x00036] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 
7dtd    |   at System.IO.Directory.CreateDirectory (System.String path) [0x0008f] in <1f0c1ef1ad524c38bbc5536809c46b48>:0 
7dtd    |   at GameManager+<StartAsServer>d__135.MoveNext () [0x00122] in <547af08b786b418cbfcf3ef2ec18045a>:0 
7dtd    |   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00027] in <316842062a1e4ad6b2fee7b9fe26257b>:0 
```
